apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: kowski-iad-core-container
  namespace: config-control
spec:
  projectRef:
    name: kowski-iad-core
  resourceID: container.googleapis.com