apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/config-control/Project/prj-bych-gke-lab001
  name: prj-bych-gke-lab001-gkehub
  namespace: config-control
spec:
  projectRef:
    name: prj-bych-gke-lab001
  resourceID: gkehub.googleapis.com
