apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: valinor-realm-sa-wi-user
  namespace: config-control
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    name: valinor-realm
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:valinor-realm.svc.id.goog[cnrm-system/cnrm-controller-manager-valinor-realm]