# apiVersion: configsync.gke.io/v1beta1
# kind: RepoSync
# metadata:
#   name: repo-sync
#   namespace: ${TENANT_PROJECT_ID}
# spec:
#   sourceFormat: unstructured
#   git:
#     repo: ${GKE_PLATFORM_REPO_URL}
#     revision: HEAD
#     branch: main
#     dir: demo/${TENANT_PROJECT_ID}/tenant
#     auth: none
