apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-admin-kowski-iad-core
  namespace: config-control
spec:
  memberFrom:
    serviceAccountRef:
      name: kowski-iad-core
  role: roles/resourcemanager.projectIamAdmin
  resourceRef:
    kind: Project
    external: projects/kowski-iad-core