apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: kowski-iad-core-sa-wi-user
  namespace: config-control
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/config-control/IAMServiceAccount/kowski-iad-core
spec:
  resourceRef:
    name: kowski-iad-core
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:kowski-iad-core.svc.id.goog[cnrm-system/cnrm-controller-manager-kowski-iad-core]