apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: kowski-iad-core-sa-wi-user
  namespace: config-control
spec:
  resourceRef:
    name: kowski-iad-core
    kind: projects/kowski-iad-core/serviceAccounts/kowski-iad-core@kowski-iad-core.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:kowski-iad-core.svc.id.goog[cnrm-system/cnrm-controller-manager-kowski-iad-core]