apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: container-admin-prj-bych-gke-lab001
  namespace: config-control
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/config-control/IAMServiceAccount/prj-bych-gke-lab001,resourcemanager.cnrm.cloud.google.com/namespaces/config-control/Project/prj-bych-gke-lab001
spec:
  memberFrom:
    serviceAccountRef:
      name: prj-bych-gke-lab001
  role: roles/container.admin
  resourceRef:
    kind: Project
    external: projects/prj-bych-gke-lab001
