apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: prj-bych-gke-lab001
subjects:
- kind: ServiceAccount
  name: ns-reconciler-prj-bych-gke-lab001
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
