apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireNamespaceConfigConnectorContext
metadata:
  name: namespaces-required-configconnectorcontext
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
    excludedNamespaces:
    - cnrm-system
    - config-control
    - config-management-monitoring
    - config-management-system
    - configconnector-operator-system
    - default
    - gatekeeper-system
    - krmapihosting-monitoring
    - krmapihosting-system
    - kube-node-lease
    - kube-public
    - kube-system
    - resource-group-system
