apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: kowski-iad-core@kowski-iad-core.iam.gserviceaccount
