apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: kowski-iad-core
spec:
  sourceFormat: unstructured
  git:
    repo: git@github.com:mbychkowski/gcp-acm-workshop-org.git
    revision: HEAD
    branch: main
    dir: demo/kowski-iad-core/tenant
    auth: none
