# apiVersion: configsync.gke.io/v1beta1
# kind: RepoSync
# metadata:
#   name: repo-sync-gke
#   namespace: valinor-realm
# spec:
#   sourceFormat: unstructured
#   git:
#     repo: git@github.com:mbychkowski/gcp-acm-workshop-org.git
#     revision: HEAD
#     branch: main
#     dir: demo/valinor-realm/gke-configs
#     auth: ssh
#     secretRef:
#       name: git-creds
