apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: first-k8s-acm-cluster
  namespace: valinor-realm
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  labels:
    mesh_id: proj-512806283726
spec:
  initialNodeCount: 1
  defaultMaxPodsPerNode: 30
  enableShieldedNodes: true
  ipAllocationPolicy:
    servicesSecondaryRangeName: svc
    clusterSecondaryRangeName: pod
  location: us-east1
  networkingMode: VPC_NATIVE
  networkRef:
    external: "https://www.googleapis.com/compute/v1/projects/valinor-realm/global/networks/main-vpc"
  nodeConfig:
    machineType: e2-standard-4
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
  releaseChannel:
    channel: RAPID
  subnetworkRef:
    external: "https://www.googleapis.com/compute/v1/projects/valinor-realm/regions/us-east1/subnetworks/main-vpc"