apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LimitLocations
metadata:
  name: allowed-locations
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups:
          - '*.cnrm.cloud.google.com'
        kinds:
          - '*'
  parameters:
    locations:
      - "northamerica-northeast1"
      - "global"
