apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: first-k8s-acm-cluster-acm-membership
  namespace: kowski-iad-core
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/kowski-iad-core/GKEHubMembership/first-k8s-acm-cluster,gkehub.cnrm.cloud.google.com/namespaces/kowski-iad-core/GKEHubFeature/configmanagement
spec:
  projectRef:
    external: kowski-iad-core
  location: global
  membershipRef:
    name: first-k8s-acm-cluster
  featureRef:
    name: configmanagement
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: demo
        secretType: none
        syncBranch: main
        syncRepo: git@github.com:mbychkowski/gcp-acm-workshop-gke-configs.git
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
    version: "1.13.0"